version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=library-mariadb
      - DB_PORT=3306
      - DB_NAME=db
      - DB_USER=user
      - DB_PASSWORD=Password
      - LOG_LEVEL=info
      - PORT=8080
    depends_on:
      - library-mariadb
    restart: unless-stopped
    networks:
      - library-network
    external_links:
      - library-mariadb

  # Using external MariaDB container
  library-mariadb:
    image: bitnami/mariadb-galera:10.11.4-debian-11-r0
    container_name: library-mariadb
    environment:
      - MARIADB_DATABASE=db
      - MARIADB_ROOT_PASSWORD=Password
      - MARIADB_USER=user
      - MARIADB_PASSWORD=Password
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - test-mariadb-vol:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - library-network

volumes:
  test-mariadb-vol:
    external: true

networks:
  library-network:
    driver: bridge